@userBase = http://localhost:4000/api/user

### SIGNUP
POST {{userBase}}/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Test@1234"
}

### LOGIN
# @name loginUser
POST {{userBase}}/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Test@1234"
}